# Generated by Django 5.2 on 2026-06-24 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='published_Date',
            new_name='published_date',
        ),
    ]
